/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.system;

import business.customer.Customer;
import business.ecosystem.EcoSystem;
import business.enterprise.Enterprise;
import business.enterprise.EnterpriseDir;
import business.network.Network;
import business.user.CustomerUser;
import business.user.SystemUser;
import business.user.User;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.LoginJFrame;
import util.DB4OUtil;

/**
 *
 * @author Shi
 */
public class SystemMainJPanel extends javax.swing.JPanel {

    private EcoSystem system = EcoSystem.getInstance();
    private SystemUser user;
    private JPanel panel;
    private JFrame frame;

    /**
     * Creates new form DeliveryManWorkAreaJPanel
     */
    public SystemMainJPanel(SystemUser user, JPanel panel, JFrame frame) {
        initComponents();
        this.user = user;
        this.panel = panel;
        this.frame = frame;
        this.nameLabel.setText("Welcome: " + user.getUsername());
        refreshNetworkList();
        refreshEnterpriseCategory();
        refreshCustomerTable();
        loadAccountDetail();
    }
    
    public void loadAccountDetail(){
        this.userNameTextField.setText(user.getUsername());
        this.firstNameTextField.setText(user.getFirstName());
        this.lastNameTextField.setText(user.getLastName());
        this.phoneTextField.setText(user.getPhoneNum());
        this.emailTextField.setText(user.getEmail());
        this.addressTextArea.setText(user.getAddress());
        this.zipCodeTextField.setText(user.getZip());
        
        this.userNameTextField.setEnabled(false);
        this.firstNameTextField.setEnabled(false);
        this.lastNameTextField.setEnabled(false);
        this.phoneTextField.setEnabled(false);
        this.emailTextField.setEnabled(false);
        this.addressTextArea.setEnabled(false);
        this.zipCodeTextField.setEnabled(false);
        
        this.saveButton.setEnabled(false);
        this.cancelButton.setEnabled(false);
    }

    public void refreshCustomerTable() {
        DefaultTableModel model = (DefaultTableModel) customerTable.getModel();
        model.setRowCount(0);
        
        for (Customer c : system.getCustomerDir().getCustomerDir()) {
            CustomerUser u = c.getCustomerUser();
            Object[] rowData = new Object[6];
            rowData[0] = u.getUsername();
            rowData[1] = c;
            rowData[2] = c.getCustomerFirstName();
            rowData[3] = c.getCustomerPhoneNum();
            rowData[4] = c.getCustomerEmail();
            rowData[5] = "TODO";

            model.addRow(rowData);
        }
        customerTable.setModel(model);
    }

    public void refreshNetworkList() {
        DefaultListModel<String> model = new DefaultListModel<>();
        for (Network network : system.getNetworkList()) {
            model.addElement(network.toString());
        }
        this.networkList.setModel(model);
    }

    public void refreshEnterpriseCategory() {
        DefaultListModel<String> model = new DefaultListModel<>();
        for (Enterprise.type type : Enterprise.type.values()) {
            model.addElement(type.name());
        }
        this.enterpriseCategoryList.setModel(model);
    }

    public void refreshEnterpriseList() {
        DefaultListModel<Enterprise> model = new DefaultListModel<>();
        for (Network n : system.getNetworkList()) {
            if (this.networkList.getSelectedValue().equals(n.getName())) {
                for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseDir()) {
                    if (this.enterpriseCategoryList.getSelectedValue() != null && this.enterpriseCategoryList.getSelectedValue().equals(e.getType().name())) {
                        model.addElement(e);
                    }
                }
            }
        }
        this.enterpriseList.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        AccountDetailPanel = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        uploadButton = new javax.swing.JButton();
        firstNameLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        userNameTextField = new javax.swing.JTextField();
        userNameLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTextArea = new javax.swing.JTextArea();
        AddressLabel = new javax.swing.JLabel();
        zipCodeLabel = new javax.swing.JLabel();
        zipCodeTextField = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        phoneTextField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        ManagePasswordPanel = new javax.swing.JPanel();
        oldPasswordLabel = new javax.swing.JLabel();
        oldPasswordTextField = new javax.swing.JTextField();
        newPasswordLabel = new javax.swing.JLabel();
        newPasswordTextField = new javax.swing.JTextField();
        confirmPasswardLabel = new javax.swing.JLabel();
        confirmPasswordTextField = new javax.swing.JTextField();
        savePwdButton = new javax.swing.JButton();
        ManageNetwork = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        networkList = new javax.swing.JList<>();
        networkCreateButton = new javax.swing.JButton();
        networkEditButton = new javax.swing.JButton();
        networkRemoveButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        enterpriseCategoryList = new javax.swing.JList<>();
        selectCategoryBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        enterpriseList = new javax.swing.JList<>();
        enterpriseEditButton = new javax.swing.JButton();
        enterpriseCreateButton = new javax.swing.JButton();
        enterpriseRemoveButton = new javax.swing.JButton();
        ManageCustomer = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        taskDetailLabel = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        createAccountBtn = new javax.swing.JButton();
        removeAccountBtn = new javax.swing.JButton();
        editAccountBtn = new javax.swing.JButton();
        deliverySearchButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();

        uploadButton.setText("Upload Photo");

        firstNameLabel.setText("First Name:");

        lastNameLabel.setText("Last Name:");

        userNameLabel.setText("User Name:");

        addressTextArea.setColumns(20);
        addressTextArea.setRows(5);
        jScrollPane1.setViewportView(addressTextArea);

        AddressLabel.setText("Address:");

        zipCodeLabel.setText("Zip Code:");

        phoneLabel.setText("Phone:");

        emailLabel.setText("Email:");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AccountDetailPanelLayout = new javax.swing.GroupLayout(AccountDetailPanel);
        AccountDetailPanel.setLayout(AccountDetailPanelLayout);
        AccountDetailPanelLayout.setHorizontalGroup(
            AccountDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountDetailPanelLayout.createSequentialGroup()
                .addGroup(AccountDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AccountDetailPanelLayout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(editButton)
                        .addGap(63, 63, 63)
                        .addComponent(saveButton)
                        .addGap(64, 64, 64)
                        .addComponent(cancelButton))
                    .addGroup(AccountDetailPanelLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addGroup(AccountDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameLabel)
                            .addComponent(lastNameLabel)
                            .addComponent(userNameLabel)
                            .addComponent(AddressLabel)
                            .addComponent(phoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailLabel))
                        .addGap(52, 52, 52)
                        .addGroup(AccountDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AccountDetailPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(zipCodeLabel)
                                .addGap(18, 18, 18)
                                .addComponent(zipCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AccountDetailPanelLayout.createSequentialGroup()
                                .addGroup(AccountDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(firstNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                    .addComponent(lastNameTextField)
                                    .addComponent(userNameTextField)
                                    .addComponent(phoneTextField)
                                    .addComponent(emailTextField))
                                .addGroup(AccountDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AccountDetailPanelLayout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(AccountDetailPanelLayout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(uploadButton)))))))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        AccountDetailPanelLayout.setVerticalGroup(
            AccountDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountDetailPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(AccountDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AccountDetailPanelLayout.createSequentialGroup()
                        .addGroup(AccountDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userNameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(AccountDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameLabel)
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(AccountDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameLabel)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AccountDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneLabel)
                            .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(AccountDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailLabel)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AccountDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(zipCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AccountDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(zipCodeLabel)
                                .addComponent(AddressLabel))))
                    .addGroup(AccountDetailPanelLayout.createSequentialGroup()
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(uploadButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(AccountDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editButton)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addGap(28, 28, 28))
        );

        jTabbedPane1.addTab("Account Detail", AccountDetailPanel);

        oldPasswordLabel.setText("Old Password:");

        newPasswordLabel.setText("New Password:");

        confirmPasswardLabel.setText("Confirm Password:");

        savePwdButton.setText("Save");
        savePwdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePwdButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ManagePasswordPanelLayout = new javax.swing.GroupLayout(ManagePasswordPanel);
        ManagePasswordPanel.setLayout(ManagePasswordPanelLayout);
        ManagePasswordPanelLayout.setHorizontalGroup(
            ManagePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManagePasswordPanelLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(ManagePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManagePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(newPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(oldPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(confirmPasswardLabel))
                .addGap(37, 37, 37)
                .addGroup(ManagePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(savePwdButton)
                    .addGroup(ManagePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(oldPasswordTextField)
                        .addComponent(newPasswordTextField)
                        .addComponent(confirmPasswordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)))
                .addContainerGap(308, Short.MAX_VALUE))
        );
        ManagePasswordPanelLayout.setVerticalGroup(
            ManagePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManagePasswordPanelLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(ManagePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldPasswordLabel)
                    .addComponent(oldPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(ManagePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPasswordLabel)
                    .addComponent(newPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(ManagePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmPasswardLabel)
                    .addComponent(confirmPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(savePwdButton)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manage Password", ManagePasswordPanel);

        jLabel1.setText("Network");

        networkList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(networkList);

        networkCreateButton.setText("Create");
        networkCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkCreateButtonActionPerformed(evt);
            }
        });

        networkEditButton.setText("Edit");
        networkEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkEditButtonActionPerformed(evt);
            }
        });

        networkRemoveButton.setText("Remove");
        networkRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkRemoveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(networkCreateButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(networkEditButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(networkRemoveButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(networkCreateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(networkEditButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(networkRemoveButton)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel2.setText("Enterprise Category");

        enterpriseCategoryList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(enterpriseCategoryList);

        selectCategoryBtn.setText("Select");
        selectCategoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectCategoryBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(selectCategoryBtn))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane4)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectCategoryBtn)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel3.setText("Enterprise");

        jScrollPane5.setViewportView(enterpriseList);

        enterpriseEditButton.setText("Edit");
        enterpriseEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseEditButtonActionPerformed(evt);
            }
        });

        enterpriseCreateButton.setText("Create");
        enterpriseCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseCreateButtonActionPerformed(evt);
            }
        });

        enterpriseRemoveButton.setText("Remove");
        enterpriseRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseRemoveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(enterpriseCreateButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(enterpriseEditButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(enterpriseRemoveButton, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterpriseCreateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterpriseEditButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterpriseRemoveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ManageNetworkLayout = new javax.swing.GroupLayout(ManageNetwork);
        ManageNetwork.setLayout(ManageNetworkLayout);
        ManageNetworkLayout.setHorizontalGroup(
            ManageNetworkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManageNetworkLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        ManageNetworkLayout.setVerticalGroup(
            ManageNetworkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageNetworkLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(ManageNetworkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manager Network", ManageNetwork);

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Last Name", "First Name", "Phone", "Email", "Order Num"
            }
        ));
        jScrollPane2.setViewportView(customerTable);

        taskDetailLabel.setText("Search:");

        createAccountBtn.setText("Create Account");
        createAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountBtnActionPerformed(evt);
            }
        });

        removeAccountBtn.setText("Remove Account");
        removeAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAccountBtnActionPerformed(evt);
            }
        });

        editAccountBtn.setText("Edit Account");
        editAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAccountBtnActionPerformed(evt);
            }
        });

        deliverySearchButton.setText("Search");

        javax.swing.GroupLayout ManageCustomerLayout = new javax.swing.GroupLayout(ManageCustomer);
        ManageCustomer.setLayout(ManageCustomerLayout);
        ManageCustomerLayout.setHorizontalGroup(
            ManageCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageCustomerLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(ManageCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManageCustomerLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(126, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManageCustomerLayout.createSequentialGroup()
                        .addGroup(ManageCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ManageCustomerLayout.createSequentialGroup()
                                .addComponent(taskDetailLabel)
                                .addGap(30, 30, 30)
                                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(createAccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ManageCustomerLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(deliverySearchButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(ManageCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(removeAccountBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(editAccountBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(135, 135, 135))))
        );
        ManageCustomerLayout.setVerticalGroup(
            ManageCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(ManageCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taskDetailLabel)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createAccountBtn))
                .addGap(18, 18, 18)
                .addGroup(ManageCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deliverySearchButton)
                    .addComponent(editAccountBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(removeAccountBtn)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manage Customer", ManageCustomer);

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        nameLabel.setText("Welcome: <name>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoutButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutButton)
                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAccountBtnActionPerformed
        // TODO add your handling code here:
        if (customerTable.getSelectedRow() != -1) {
            Customer c = (Customer) customerTable.getValueAt(customerTable.getSelectedRow(), 1);
            CreateCustomerAccountJFrame cjframe = new CreateCustomerAccountJFrame(this, true, c, null);
            cjframe.setLocationRelativeTo(null);
            cjframe.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Please select customer");
        }

    }//GEN-LAST:event_editAccountBtnActionPerformed

    private void removeAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAccountBtnActionPerformed
        // TODO add your handling code here:
        if (customerTable.getSelectedRow() != -1) {
            Customer c = (Customer) customerTable.getValueAt(customerTable.getSelectedRow(), 1);
            system.getCustomerDir().removeCustomer(c);
            this.refreshCustomerTable();
        } else {
            JOptionPane.showMessageDialog(null, "Please select customer");
        }
    }//GEN-LAST:event_removeAccountBtnActionPerformed

    private void networkCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkCreateButtonActionPerformed
        // TODO add your handling code here:
        NetworkJFrame networkFrame = new NetworkJFrame(this, false, null);
        networkFrame.setLocationRelativeTo(null);
        networkFrame.setVisible(true);
    }//GEN-LAST:event_networkCreateButtonActionPerformed

    private void enterpriseCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseCreateButtonActionPerformed
        // TODO add your handling code here:
        if (this.networkList.getSelectedValue() != null) {
            EnterpriseDir edir = null;
            for (Network n : system.getNetworkList()) {
                if (this.networkList.getSelectedValue().equalsIgnoreCase(n.getName())) {
                    edir = n.getEnterpriseDirectory();
                }
            }
            EnterpriseJFrame eJFrame = new EnterpriseJFrame(this, false, null, edir);
            eJFrame.setLocationRelativeTo(null);
            eJFrame.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Please select network");
        }

    }//GEN-LAST:event_enterpriseCreateButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        DB4OUtil.getInstance().storeSystem(system);
        frame.dispose();
        LoginJFrame lFrame = new LoginJFrame();
        lFrame.setLocationRelativeTo(null);
        lFrame.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void selectCategoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectCategoryBtnActionPerformed
        // TODO add your handling code here:
        if (this.enterpriseCategoryList.getSelectedValue() != null && this.networkList.getSelectedValue() != null) {
            refreshEnterpriseList();
        } else {
            JOptionPane.showMessageDialog(null, "Please select network and one enterprise category");
        }

    }//GEN-LAST:event_selectCategoryBtnActionPerformed

    private void networkEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkEditButtonActionPerformed
        // TODO add your handling code here:
        if (this.networkList.getSelectedValue() != null) {
            NetworkJFrame networkFrame = new NetworkJFrame(this, true, this.networkList.getSelectedValue());
            networkFrame.setLocationRelativeTo(null);
            networkFrame.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Please select network");
        }

    }//GEN-LAST:event_networkEditButtonActionPerformed

    private void networkRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkRemoveButtonActionPerformed
        // TODO add your handling code here:
        if (this.networkList.getSelectedValue() != null) {
            system.removeNetwork(this.networkList.getSelectedValue());
            refreshNetworkList();
        } else {
            JOptionPane.showMessageDialog(null, "Please select network");
        }
    }//GEN-LAST:event_networkRemoveButtonActionPerformed

    private void enterpriseEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseEditButtonActionPerformed
        // TODO add your handling code here:
        if (this.enterpriseList.getSelectedValue() != null) {
            EnterpriseJFrame eJFrame = new EnterpriseJFrame(this, true, this.enterpriseList.getSelectedValue(), null);
            eJFrame.setLocationRelativeTo(null);
            eJFrame.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Please select enterprise");
        }

    }//GEN-LAST:event_enterpriseEditButtonActionPerformed

    private void enterpriseRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseRemoveButtonActionPerformed
        // TODO add your handling code here:
        if (this.enterpriseList.getSelectedValue() != null) {
            for (Network w : system.getNetworkList()) {
                for (Enterprise e : w.getEnterpriseDirectory().getEnterpriseDir()) {
                    if (this.enterpriseList.getSelectedValue().getName().equals(e.getName()) && this.enterpriseList.getSelectedValue().getType().equals(e.getType())) {
                        w.getEnterpriseDirectory().getEnterpriseDir().remove(e);
                        DB4OUtil.getInstance().storeSystem(system);
                        refreshEnterpriseList();
                        return;
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select network");
        }
    }//GEN-LAST:event_enterpriseRemoveButtonActionPerformed

    private void createAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountBtnActionPerformed
        // TODO add your handling code here:
        CreateCustomerAccountJFrame cjframe = new CreateCustomerAccountJFrame(this, false, null, system.getCustomerDir());
        cjframe.setLocationRelativeTo(null);
        cjframe.setVisible(true);
    }//GEN-LAST:event_createAccountBtnActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        loadAccountDetail();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        this.firstNameTextField.setEnabled(true);
        this.lastNameTextField.setEnabled(true);
        this.phoneTextField.setEnabled(true);
        this.emailTextField.setEnabled(true);
        this.addressTextArea.setEnabled(true);
        this.zipCodeTextField.setEnabled(true);
        
        saveButton.setEnabled(true);
        cancelButton.setEnabled(true);
    }//GEN-LAST:event_editButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        String firstName = this.firstNameTextField.getText();
        String lastName = this.lastNameTextField.getText();
        String phone = this.phoneTextField.getText();
        String email = this.emailTextField.getText();
        String address = this.addressTextArea.getText();
        String zipcode = this.zipCodeTextField.getText();
        
        if (!"".equals(firstName) && !"".equals(lastName) && !"".equals(phone) && !"".equals(email) && !"".equals(address) && !"".equals(zipcode)){
            user.setLastName(lastName);
            user.setFirstName(firstName);
            user.setEmail(email);
            user.setAddress(address);
            user.setPhoneNum(phone);
            user.setZip(zipcode);
            loadAccountDetail();
            DB4OUtil.getInstance().storeSystem(system);
        } else {
            JOptionPane.showMessageDialog(null, "Please enter valid input");
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void savePwdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePwdButtonActionPerformed
        // TODO add your handling code here:
        String oldpwd = this.oldPasswordTextField.getText();
        String newpwd = this.newPasswordTextField.getText();
        String confirmpwd = this.confirmPasswordTextField.getText();
        if (!"".equals(oldpwd) && !"".equals(newpwd) && !"".equals(confirmpwd) ){
            if (newpwd.equals(confirmpwd)){
                if (oldpwd.equals(user.getPassword())){
                    user.setPassword(newpwd);
                    DB4OUtil.getInstance().storeSystem(system);
                    this.oldPasswordTextField.setText("");
                    this.newPasswordTextField.setText("");
                    this.confirmPasswordTextField.setText("");
                    JOptionPane.showMessageDialog(null, "Update password successfully");
                } else {
                    JOptionPane.showMessageDialog(null, "Please enter old password correctly");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please enter same password");
            }
        }else {
             JOptionPane.showMessageDialog(null, "Please enter valid input");
        }
    }//GEN-LAST:event_savePwdButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccountDetailPanel;
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JPanel ManageCustomer;
    private javax.swing.JPanel ManageNetwork;
    private javax.swing.JPanel ManagePasswordPanel;
    private javax.swing.JTextArea addressTextArea;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel confirmPasswardLabel;
    private javax.swing.JTextField confirmPasswordTextField;
    private javax.swing.JButton createAccountBtn;
    private javax.swing.JTable customerTable;
    private javax.swing.JButton deliverySearchButton;
    private javax.swing.JButton editAccountBtn;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JList<String> enterpriseCategoryList;
    private javax.swing.JButton enterpriseCreateButton;
    private javax.swing.JButton enterpriseEditButton;
    private javax.swing.JList<Enterprise> enterpriseList;
    private javax.swing.JButton enterpriseRemoveButton;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton networkCreateButton;
    private javax.swing.JButton networkEditButton;
    private javax.swing.JList<String> networkList;
    private javax.swing.JButton networkRemoveButton;
    private javax.swing.JLabel newPasswordLabel;
    private javax.swing.JTextField newPasswordTextField;
    private javax.swing.JLabel oldPasswordLabel;
    private javax.swing.JTextField oldPasswordTextField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JButton removeAccountBtn;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton savePwdButton;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JButton selectCategoryBtn;
    private javax.swing.JLabel taskDetailLabel;
    private javax.swing.JButton uploadButton;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField userNameTextField;
    private javax.swing.JLabel zipCodeLabel;
    private javax.swing.JTextField zipCodeTextField;
    // End of variables declaration//GEN-END:variables

}
