/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.customer;

import business.customer.ShoppingCart;
import business.ecosystem.EcoSystem;
import business.furniture.Furniture;
import business.network.Network;
import business.user.CustomerUser;
import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.LoginJFrame;
import util.DB4OUtil;

/**
 *
 * @author Shi
 */
public class CustomerPanel extends javax.swing.JPanel {

    private EcoSystem system = EcoSystem.getInstance();
    private CustomerUser user;
    private JPanel panel;
    private JFrame frame;
    private ShoppingCart cart;

    /**
     * Creates new form CustomerPanel
     */
    public CustomerPanel(CustomerUser user, JPanel panel, JFrame frame) {
        initComponents();
        this.user = user;
        this.panel = panel;
        this.frame = frame;
        this.titleLabel.setText("Customer " + user.getUsername());

        DefaultComboBoxModel dcbm = (DefaultComboBoxModel) cityComboBox.getModel();
        for (Network n : system.getNetworkList()) {
            dcbm.addElement(n);
        }
        this.cityComboBox.setModel(dcbm);

        DefaultComboBoxModel dcbm1 = (DefaultComboBoxModel) categoryComboBox.getModel();
        for (Furniture.category c : Furniture.category.values()) {
            dcbm1.addElement(c);
        }
        this.categoryComboBox.setModel(dcbm1);

        this.cart = new ShoppingCart();
    }

    public void loadFurnitureTable() {
        Network n = (Network) cityComboBox.getSelectedItem();
        Furniture.category c = (Furniture.category) categoryComboBox.getSelectedItem();

        DefaultTableModel dtm = (DefaultTableModel) furnitureTable.getModel();
        dtm.setRowCount(0);
        for (Furniture f : n.getFurnitureDir().getFurnitureDir()) {
            if (f.getCategory().equals(c)) {
                Object[] rowData = new Object[5];
                rowData[0] = f;
                rowData[1] = f.getBrand();
                rowData[2] = f.getOwner();
                rowData[3] = f.getPrice();
                rowData[4] = f.getQuantity();
                dtm.addRow(rowData);
            }
        }
        furnitureTable.setModel(dtm);
        this.cityComboBox.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        furnitureTable = new javax.swing.JTable();
        addCartButton = new javax.swing.JButton();
        viewCart = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        sellerButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        myButton = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        cityComboBox = new javax.swing.JComboBox<>();
        categoryComboBox = new javax.swing.JComboBox<>();
        rentButton = new javax.swing.JButton();

        jLabel1.setText("City(Network):");

        jLabel2.setText("Category:");

        furnitureTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Brand", "Owner", "Price", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(furnitureTable);

        addCartButton.setText("Add to Cart");
        addCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCartButtonActionPerformed(evt);
            }
        });

        viewCart.setText("View Cart");
        viewCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCartActionPerformed(evt);
            }
        });

        titleLabel.setText("Customer <Name>");

        sellerButton.setText("I want to be a seller!");
        sellerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellerButtonActionPerformed(evt);
            }
        });

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        myButton.setText("My");
        myButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButtonActionPerformed(evt);
            }
        });

        searchBtn.setText("Select");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        rentButton.setText("I want to rent a warehouse!");
        rentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(addCartButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewCart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sellerButton)
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(cityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(searchBtn)))
                        .addContainerGap(20, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(myButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoutButton)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rentButton)
                        .addGap(264, 264, 264))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutButton)
                    .addComponent(myButton)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(cityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchBtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCartButton)
                    .addComponent(viewCart)
                    .addComponent(sellerButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(rentButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        DB4OUtil.getInstance().storeSystem(system);
        frame.dispose();
        LoginJFrame lFrame = new LoginJFrame();
        lFrame.setLocationRelativeTo(null);
        lFrame.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void myButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButtonActionPerformed
        // TODO add your handling code here:
        MyPanel mpanel = new MyPanel(panel,user);
        this.panel.add(mpanel);
        CardLayout layout = (CardLayout) this.panel.getLayout();
        layout.next(this.panel);
    }//GEN-LAST:event_myButtonActionPerformed

    private void sellerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellerButtonActionPerformed
        // TODO add your handling code here:
        SellFurniture panel = new SellFurniture(this.panel, user,(Network) cityComboBox.getSelectedItem());
        this.panel.add(panel);
        CardLayout layout = (CardLayout) this.panel.getLayout();
        layout.next(this.panel);
    }//GEN-LAST:event_sellerButtonActionPerformed

    private void viewCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCartActionPerformed
        // TODO add your handling code here:
        CartPanel cPanel = new CartPanel(this.panel, cart, user,(Network) cityComboBox.getSelectedItem());
        this.panel.add(cPanel);
        CardLayout layout = (CardLayout) this.panel.getLayout();
        layout.next(this.panel);
    }//GEN-LAST:event_viewCartActionPerformed

    private void addCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCartButtonActionPerformed
        // TODO add your handling code here:
        if (furnitureTable.getSelectedRow() != -1) {
            Furniture f = (Furniture) furnitureTable.getValueAt(furnitureTable.getSelectedRow(), 0);
            int maxQ = f.getQuantity();
            int shoppingCartQ = cart.getFurnitureDir().getFurniture(f) != null ? cart.getFurnitureDir().getFurniture(f).getShoppingQuantity(): 0;
            JFrame frame = new JFrame();
            try {
                int q = Integer.valueOf(JOptionPane.showInputDialog(frame, "Enter your quantity"));
                if (q > maxQ - shoppingCartQ || q == 0) {
                    JOptionPane.showMessageDialog(null, "input valid number");
                } else {
                    Furniture f1 = new Furniture(true, f.getName(), f.getBrand(), f.getCategory(), f.getPrice() , f.getQuantity() , f.getOwner() , f.getWarehouse() );
                    f1.setShoppingQuantity(q);
                    cart.getFurnitureDir().addFurniture(f1);
                    JOptionPane.showMessageDialog(null, "add successfully");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "input valid number");
            }
        } else {
            JOptionPane.showMessageDialog(null, "select one furniture");
        }


    }//GEN-LAST:event_addCartButtonActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        loadFurnitureTable();
        
    }//GEN-LAST:event_searchBtnActionPerformed

    private void rentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentButtonActionPerformed
        // TODO add your handling code here:
        RentWarehousePanel panel = new RentWarehousePanel(this.panel, user,(Network) cityComboBox.getSelectedItem());
        this.panel.add(panel);
        CardLayout layout = (CardLayout) this.panel.getLayout();
        layout.next(this.panel);
    }//GEN-LAST:event_rentButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCartButton;
    private javax.swing.JComboBox<String> categoryComboBox;
    private javax.swing.JComboBox<String> cityComboBox;
    private javax.swing.JTable furnitureTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton myButton;
    private javax.swing.JButton rentButton;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton sellerButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton viewCart;
    // End of variables declaration//GEN-END:variables
}
